symbols:
  - SOL/USDC:USDC
rate: "0 * * * *"
timeframe: "1h"
leverage: 5
position_notional_value: 250.0
atr_stop_loss: 1.4
enable_trading: true
params:
  ema_window: 8
  smooth_window: 12
  polyorder: 5