DROP TABLE TRADES;

CREATE TABLE TRADES (
	id SERIAL NOT NULL PRIMARY KEY,
	datetime TIMESTAMP NOT NULL DEFAULT NOW(),
	symbol VARCHAR(50) NOT NULL,
	qty NUMERIC NOT NULL,
	price NUMERIC NOT NULL
);

INSERT INTO TRADES (symbol, qty, price) VALUES ('ETH', 100, 3000);
INSERT INTO TRADES (symbol, qty, price) VALUES ('ETH', 200, 3500);

